services:
  api-talkpacific:
    build:
      context: ./api-talkpacific
      dockerfile: Dockerfile
    container_name: talkpacific-api-container
    env_file: ./api-talkpacific/.env
    ports:
      - "5050:5050"
    volumes:
      - ./api-talkpacific:/usr/api-talkpacific

  web-talkpacific:
    image: node:latest
    container_name: talkpacific-web-container
    working_dir: /app
    environment:
      - NODE_ENV=development
    env_file: ./app-desktop-react/.env
    volumes:
      - ./app-desktop-react:/app
    ports:
      - "8080:3000"
    command: /bin/bash -c "npm install && npm run start-react"
